// Generated by scripts/generate.ts. Don't edit.
import type { ParsedTable } from "@workspace.sh/table-core";
import { projectsTable } from "./projects";
import { tasksTable } from "./tasks";

export { projectsTable } from "./projects";
export { tasksTable } from "./tasks";

/**
 * Every fixture, keyed as a relation's `table` names it: the directory's
 * name without `.table`. The web demo builds the same map from disk.
 */
export const tables: Record<string, ParsedTable> = {
  "projects": projectsTable,
  "tasks": tasksTable,
};
