// Generated by scripts/generate.ts. Don't edit.
import type { ParsedTable } from "@workspace.sh/table-core";
import { companiesTable } from "./companies";
import { contactsTable } from "./contacts";
import { dealsTable } from "./deals";
import { projectsTable } from "./projects";
import { tasksTable } from "./tasks";

export { companiesTable } from "./companies";
export { contactsTable } from "./contacts";
export { dealsTable } from "./deals";
export { projectsTable } from "./projects";
export { tasksTable } from "./tasks";

/**
 * Every fixture, keyed as a relation's `table` names it: the directory's
 * name without `.table`. The web demo builds the same map from disk.
 */
export const tables: Record<string, ParsedTable> = {
  "companies": companiesTable,
  "contacts": contactsTable,
  "deals": dealsTable,
  "projects": projectsTable,
  "tasks": tasksTable,
};
