// Runs every case in the suite through each engine and writes the
// report: per OpenFormula function, how many cases each engine meets.
//
//   npm run run -w @workspace.sh/table-conformance

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { meets } from "./compare.js";
import { type Case, printNode, printValue, readCases } from "./edn.js";
import { hostSensitive, sameHost, type Value } from "./node.js";
import { type Engine, formualizer, tableCore } from "./engines.js";

const here = dirname(fileURLToPath(import.meta.url));
const suite = join(here, "../../../conformance/openformula");
const require = (p: string) => JSON.parse(readFileSync(join(here, "..", "node_modules", p), "utf8")) as { version: string };
const rootRequire = (p: string) => JSON.parse(readFileSync(join(here, "../../../node_modules", p), "utf8")) as { version: string };

function version(pkg: string): string {
  try {
    return require(`${pkg}/package.json`).version;
  } catch {
    return rootRequire(`${pkg}/package.json`).version;
  }
}

const engines: Engine[] = [
  formualizer(version("formualizer")),
  tableCore(JSON.parse(readFileSync(join(here, "../../core/package.json"), "utf8")).version),
];

const openformula = readFileSync(join(suite, "functions.txt"), "utf8")
  .split("\n")
  .filter((l) => l && !l.startsWith("#"));

function ednFiles(dir: string): string[] {
  return readdirSync(dir)
    .sort()
    .flatMap((name) => {
      const p = join(dir, name);
      if (statSync(p).isDirectory()) return ednFiles(p);
      return name.endsWith(".edn") ? [p] : [];
    });
}

/** An engine's answer for the report; it may be something EDN can't hold, like Infinity. */
function shown(v: Value): string {
  try {
    return printValue(v);
  } catch {
    return String(v);
  }
}

interface Tally {
  cases: number;
  met: Map<string, number>;
  /** Not met, under the host settings the engine uses: a real miss. */
  missed: Map<string, number>;
  /** Not met, but the case was written under other host settings, so the miss may be theirs. */
  inconclusive: Map<string, number>;
  firstMiss: Map<string, string>;
}

const bump = (m: Map<string, number>, k: string) => m.set(k, (m.get(k) ?? 0) + 1);

// A source file tests one function, named by the file: round.edn, or
// networkdays.intl.edn. LibreOffice's name for an Excel function carries
// com.microsoft., which the file name drops.
const byFunction = new Map<string, Tally>();
const sources = new Set<string>();

for (const file of ednFiles(suite)) {
  const fn = file.split("/").pop()!.replace(/\.edn$/, "");
  const source = relative(suite, file).split("/")[0]!;
  sources.add(source);
  let cases: Case[];
  try {
    cases = readCases(readFileSync(file, "utf8"));
  } catch (e) {
    console.error(`${relative(suite, file)}: ${String(e)}`);
    process.exitCode = 1;
    continue;
  }
  const t = byFunction.get(fn) ?? { cases: 0, met: new Map(), missed: new Map(), inconclusive: new Map(), firstMiss: new Map() };
  byFunction.set(fn, t);
  for (const c of cases) {
    t.cases++;
    for (const engine of engines) {
      const got = engine.evaluate(c);
      const expressed = !(typeof got === "object" && got !== null && !Array.isArray(got) && "cannotExpress" in got);
      if (expressed && meets(got, c.expect, c.compare)) {
        bump(t.met, engine.name);
        continue;
      }
      if (expressed && !sameHost(c.host, engine.host) && hostSensitive(c.expr)) {
        bump(t.inconclusive, engine.name);
        continue;
      }
      bump(t.missed, engine.name);
      if (!t.firstMiss.has(engine.name)) {
        const gave = expressed ? shown(got as Value) : "nothing (can't express it)";
        t.firstMiss.set(engine.name, `${printNode(c.expr)} gave ${gave}, expected ${printValue(c.expect)}`);
      }
    }
  }
}

// ---- the report

const inSpec = openformula.filter((f) => byFunction.has(f));
const untested = openformula.filter((f) => !byFunction.has(f));
const specCases = inSpec.reduce((n, f) => n + byFunction.get(f)!.cases, 0);

const lines: string[] = [];
lines.push("# OpenFormula conformance");
lines.push("");
lines.push("Generated by `npm run run -w @workspace.sh/table-conformance`. Don't edit by hand.");
lines.push("");
lines.push(`Cases come from: ${[...sources].sort().join(", ")} (see each directory's SOURCE.json).`);
lines.push(
  `OpenFormula 1.4 has ${openformula.length} functions (functions.txt); ${inSpec.length} have cases here (${specCases} cases), ${untested.length} have none yet.`,
);
lines.push("");
lines.push("| Engine | Version | Functions with no misses | Cases met | Missed | Inconclusive |");
lines.push("| --- | --- | --- | --- | --- | --- |");
const sum = (m: (t: Tally) => number) => inSpec.reduce((n, f) => n + m(byFunction.get(f)!), 0);
for (const e of engines) {
  const clean = inSpec.filter((f) => (byFunction.get(f)!.missed.get(e.name) ?? 0) === 0 && (byFunction.get(f)!.met.get(e.name) ?? 0) > 0).length;
  lines.push(
    `| ${e.name} | ${e.version} | ${clean} of ${inSpec.length} | ${sum((t) => t.met.get(e.name) ?? 0)} of ${specCases} | ` +
      `${sum((t) => t.missed.get(e.name) ?? 0)} | ${sum((t) => t.inconclusive.get(e.name) ?? 0)} |`,
  );
}
lines.push("");
lines.push(
  "A **miss** is a wrong answer under the host settings the engine computes with (OpenFormula 3.4; `.table`'s are Excel's, DECISIONS D39). " +
    "A case written under other settings, using something those settings change (criteria, database functions, lookups, `search`, comparisons), " +
    "that an engine doesn't meet is **inconclusive**: the difference may be the settings'. " +
    "A function has no misses when at least one case is met and none is missed. A case an engine can't express counts as missed.",
);
lines.push("");
lines.push("## By function");
lines.push("");
lines.push(`| Function | Cases | ${engines.map((e) => `${e.name} met / missed`).join(" | ")} | First miss (${engines[0]!.name}) |`);
lines.push(`| --- | --- | ${engines.map(() => "---").join(" | ")} | --- |`);
const cell = (s: string) => s.replace(/\|/g, "\\|").slice(0, 160);
for (const f of inSpec) {
  const t = byFunction.get(f)!;
  const counts = engines.map((e) => {
    const met = t.met.get(e.name) ?? 0, missed = t.missed.get(e.name) ?? 0;
    return `${met} / ${missed}${missed === 0 && met > 0 ? " ✓" : ""}`;
  });
  lines.push(`| \`${f}\` | ${t.cases} | ${counts.join(" | ")} | ${cell(t.firstMiss.get(engines[0]!.name) ?? "")} |`);
}
lines.push("");
lines.push("## OpenFormula functions with no cases yet");
lines.push("");
lines.push(untested.map((f) => `\`${f}\``).join(", ") || "None.");
lines.push("");
const outside = [...byFunction.keys()].filter((f) => !openformula.includes(f)).sort();
lines.push("## Cases for functions outside OpenFormula");
lines.push("");
lines.push("Imported with their sources, not counted above: later layers (DECISIONS D38) or LibreOffice's own functions.");
lines.push("");
lines.push(outside.map((f) => `\`${f}\` (${byFunction.get(f)!.cases})`).join(", "));
lines.push("");

writeFileSync(join(suite, "REPORT.md"), lines.join("\n"));
console.log(lines.slice(0, 12).join("\n"));
