// Runs every case in the suite through each engine and writes the
// report: per OpenFormula function, how many cases each engine meets.
//
//   npm run run -w @workspace.sh/table-conformance

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { meets } from "./compare.js";
import { type Case, printNode, printValue, readCases } from "./edn.js";
import type { Value } from "./node.js";
import { type Engine, formualizer, tableCore } from "./engines.js";

const here = dirname(fileURLToPath(import.meta.url));
const suite = join(here, "../../../conformance/openformula");
const require = (p: string) => JSON.parse(readFileSync(join(here, "..", "node_modules", p), "utf8")) as { version: string };
const rootRequire = (p: string) => JSON.parse(readFileSync(join(here, "../../../node_modules", p), "utf8")) as { version: string };

function version(pkg: string): string {
  try {
    return require(`${pkg}/package.json`).version;
  } catch {
    return rootRequire(`${pkg}/package.json`).version;
  }
}

const engines: Engine[] = [
  formualizer(version("formualizer")),
  tableCore(JSON.parse(readFileSync(join(here, "../../core/package.json"), "utf8")).version),
];

const openformula = readFileSync(join(suite, "functions.txt"), "utf8")
  .split("\n")
  .filter((l) => l && !l.startsWith("#"));

function ednFiles(dir: string): string[] {
  return readdirSync(dir)
    .sort()
    .flatMap((name) => {
      const p = join(dir, name);
      if (statSync(p).isDirectory()) return ednFiles(p);
      return name.endsWith(".edn") ? [p] : [];
    });
}

/** An engine's answer for the report; it may be something EDN can't hold, like Infinity. */
function shown(v: Value): string {
  try {
    return printValue(v);
  } catch {
    return String(v);
  }
}

interface Tally {
  cases: number;
  met: Map<string, number>;
  cannotExpress: Map<string, number>;
  firstMiss: Map<string, string>;
}

// A source file tests one function, named by the file: round.edn, or
// networkdays.intl.edn. LibreOffice's name for an Excel function carries
// com.microsoft., which the file name drops.
const byFunction = new Map<string, Tally>();
const sources = new Set<string>();

for (const file of ednFiles(suite)) {
  const fn = file.split("/").pop()!.replace(/\.edn$/, "");
  const source = relative(suite, file).split("/")[0]!;
  sources.add(source);
  let cases: Case[];
  try {
    cases = readCases(readFileSync(file, "utf8"));
  } catch (e) {
    console.error(`${relative(suite, file)}: ${String(e)}`);
    process.exitCode = 1;
    continue;
  }
  const t = byFunction.get(fn) ?? { cases: 0, met: new Map(), cannotExpress: new Map(), firstMiss: new Map() };
  byFunction.set(fn, t);
  for (const c of cases) {
    t.cases++;
    for (const engine of engines) {
      const got = engine.evaluate(c.expr);
      if (typeof got === "object" && got !== null && !Array.isArray(got) && "cannotExpress" in got) {
        t.cannotExpress.set(engine.name, (t.cannotExpress.get(engine.name) ?? 0) + 1);
        continue;
      }
      if (meets(got, c.expect, c.compare)) t.met.set(engine.name, (t.met.get(engine.name) ?? 0) + 1);
      else if (!t.firstMiss.has(engine.name)) {
        t.firstMiss.set(engine.name, `${printNode(c.expr)} gave ${shown(got)}, expected ${printValue(c.expect)}`);
      }
    }
  }
}

// ---- the report

const inSpec = openformula.filter((f) => byFunction.has(f));
const untested = openformula.filter((f) => !byFunction.has(f));
const specCases = inSpec.reduce((n, f) => n + byFunction.get(f)!.cases, 0);

const lines: string[] = [];
lines.push("# OpenFormula conformance");
lines.push("");
lines.push("Generated by `npm run run -w @workspace.sh/table-conformance`. Don't edit by hand.");
lines.push("");
lines.push(`Cases come from: ${[...sources].sort().join(", ")} (see each directory's SOURCE.json).`);
lines.push(
  `OpenFormula 1.4 has ${openformula.length} functions (functions.txt); ${inSpec.length} have cases here (${specCases} cases), ${untested.length} have none yet.`,
);
lines.push("");
lines.push("| Engine | Version | OpenFormula functions fully met | Cases met |");
lines.push("| --- | --- | --- | --- |");
for (const e of engines) {
  const full = inSpec.filter((f) => (byFunction.get(f)!.met.get(e.name) ?? 0) === byFunction.get(f)!.cases).length;
  const met = inSpec.reduce((n, f) => n + (byFunction.get(f)!.met.get(e.name) ?? 0), 0);
  lines.push(`| ${e.name} | ${e.version} | ${full} of ${inSpec.length} | ${met} of ${specCases} |`);
}
lines.push("");
lines.push("A function is fully met when every one of its cases is. A case an engine can't express at all counts as not met.");
lines.push("");
lines.push("## By function");
lines.push("");
lines.push(`| Function | Cases | ${engines.map((e) => e.name).join(" | ")} | First miss (${engines[0]!.name}) |`);
lines.push(`| --- | --- | ${engines.map(() => "---").join(" | ")} | --- |`);
const cell = (s: string) => s.replace(/\|/g, "\\|").slice(0, 160);
for (const f of inSpec) {
  const t = byFunction.get(f)!;
  const counts = engines.map((e) => {
    const met = t.met.get(e.name) ?? 0;
    return met === t.cases ? `${met} ✓` : String(met);
  });
  lines.push(`| \`${f}\` | ${t.cases} | ${counts.join(" | ")} | ${cell(t.firstMiss.get(engines[0]!.name) ?? "")} |`);
}
lines.push("");
lines.push("## OpenFormula functions with no cases yet");
lines.push("");
lines.push(untested.map((f) => `\`${f}\``).join(", ") || "None.");
lines.push("");
const outside = [...byFunction.keys()].filter((f) => !openformula.includes(f)).sort();
lines.push("## Cases for functions outside OpenFormula");
lines.push("");
lines.push("Imported with their sources, not counted above: later layers (DECISIONS D38) or LibreOffice's own functions.");
lines.push("");
lines.push(outside.map((f) => `\`${f}\` (${byFunction.get(f)!.cases})`).join(", "));
lines.push("");

writeFileSync(join(suite, "REPORT.md"), lines.join("\n"));
console.log(lines.slice(0, 12).join("\n"));
