// Writes src/<name>.ts and src/index.ts from the canonical fixtures/*.table/.
//
// Metro (mobile, desktop) can't import arbitrary files the way Vite can,
// so these demos need each fixture as a TypeScript module. Generated, not
// copied by hand: hand copies drift from the files they mirror.
//
//   npm run generate -w @workspace.sh/table-fixtures           write them
//   npm run generate -w @workspace.sh/table-fixtures -- --check fail if stale

import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { parseTable } from "../../core/src/parser.ts";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..", "..", "..");
const fixturesDir = resolve(root, "fixtures");
const srcDir = resolve(here, "..", "src");
const check = process.argv.includes("--check");

/** reading-list → readingListTable */
function exportName(key: string): string {
  return key.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase()) + "Table";
}

const names = (await readdir(fixturesDir)).filter((n) => n.endsWith(".table")).sort();
const files: Record<string, string> = {};
const keys: string[] = [];

for (const dir of names) {
  const key = dir.slice(0, -".table".length);
  const table = await parseTable(resolve(fixturesDir, dir));
  if (table.diagnostics?.length) throw new Error(`fixtures/${dir} doesn't read cleanly: ${JSON.stringify(table.diagnostics)}`);
  const { diagnostics: _none, ...clean } = table;
  keys.push(key);
  files[`${key}.ts`] =
    `// Generated from fixtures/${dir} by scripts/generate.ts. Don't edit: change\n` +
    `// the fixture and run \`npm run generate -w @workspace.sh/table-fixtures\`.\n` +
    `import type { ParsedTable } from "@workspace.sh/table-core";\n\n` +
    `export const ${exportName(key)}: ParsedTable = ${JSON.stringify({ ...clean, path: `fixtures/${dir}` }, null, 2)};\n`;
}

files["index.ts"] =
  `// Generated by scripts/generate.ts. Don't edit.\n` +
  `import type { ParsedTable } from "@workspace.sh/table-core";\n` +
  keys.map((k) => `import { ${exportName(k)} } from "./${k}";`).join("\n") +
  "\n\n" +
  keys.map((k) => `export { ${exportName(k)} } from "./${k}";`).join("\n") +
  `\n\n/**\n * Every fixture, keyed as a relation's \`table\` names it: the directory's\n * name without \`.table\`. The web demo builds the same map from disk.\n */\n` +
  `export const tables: Record<string, ParsedTable> = {\n` +
  keys.map((k) => `  ${JSON.stringify(k)}: ${exportName(k)},`).join("\n") +
  `\n};\n`;

const stale: string[] = [];
for (const [file, content] of Object.entries(files)) {
  const path = resolve(srcDir, file);
  const current = await readFile(path, "utf8").catch(() => null);
  if (current === content) continue;
  if (check) stale.push(file);
  else await writeFile(path, content);
}
if (check && stale.length > 0) {
  console.error(`Out of date with fixtures/: ${stale.join(", ")}. Run npm run generate -w @workspace.sh/table-fixtures.`);
  process.exit(1);
}
console.log(check ? "table-fixtures matches fixtures/." : `Wrote ${Object.keys(files).join(", ")}.`);
